apiVersion: 0.1.0
gitVersion:
  commitSha: b497fd581c823ba3911296ec58c072a48c57c474
  refSpec: v0.1.2
kind: ksonnet.io/registry
libraries:
  argo:
    path: argo
    version: master
  core:
    path: core
    version: master
  tf-job:
    path: tf-job
    version: master
  tf-serving:
    path: tf-serving
    version: master
