kind: ConfigMap
apiVersion: v1
metadata:
  name: imanager-config
data:
  k8s.master.url: "https://127.0.0.1:6443"
  kibana.url: "http://127.0.0.1:30003"
  kibana.port: "30003"
#access.entry.ip: "127.0.0.1"
  image.pull.policy: IfNotPresent
  grafana.service.name: grafana
  gateway.service.name: iserver-gateway
  registry: registry.cn-beijing.aliyuncs.com
  gis.application.limit.cpu: "2"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-dashboard-token
  labels:
    kind: imanager-base
data:
  token: 
eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi1zYnFqbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRiYTkyYmZiLTk0YzctMTFlOC05NThhLTAyNTAwMDAwMDAwMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprdWJlcm5ldGVzLWRhc2hib2FyZCJ9.uWR2XDVQUZqDImAQD7KlU7Ha6NXSoGmjVmz1zc77yZC_PGxut90git8yYFgTANgUzPKjHODxsqXpC8sJ9d71sG4EoG7UZVC86o8A9VP97Ir6rFSiR6GNCpoD2CJ1U49cA51pOJ22LWPlqQXFf2Izd2zSxSS_D2advbYHkOdaNGVNAkgSz8v-FXtO3YCJz29Z6cCcw4fYCOXRjEbQ9CmD8wAnRHeS_ZnWpGwSUU4DvgGfeUwLxyUeYG9NQ975FU-ffn0XGZeHXaBYi0JHRqTjjLJaB17LdHTx1YwDXhS8cXXJY21WimPMAjx1Y-wxgdDAi4xr3LAfGrVM9aRJGUersQ
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |
   route:
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'wechat'
   receivers:
   - name: 'wechat'
     wechat_configs:
      - corp_id: 'ww87015933668aaa18'
        to_party: '1'
        agent_id: '1000002'
        api_secret: 'w_sxF80QHT3qJ2y3whmcBqYkwim6Vqw-N2L-_axb04w'
        message: '{{ template "wechat.imanager.message" . }}'
   templates:
     - 'templates/*.tmpl'
