kind: ConfigMap
apiVersion: v1
metadata:
  name: imanager-config
data:
  k8s.master.url: "https://127.0.0.1:6443"
  kibana.url: "http://127.0.0.1:30003"
  kibana.port: "30003"
  access.entry.ip: 127.0.0.1
  image.pull.policy: IfNotPresent
  grafana.service.name: grafana
  gateway.service.name: iserver-gateway
  registry: registry.cn-beijing.aliyuncs.com
  gis.application.limit.cpu: "2"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-dashboard-token
  labels:
    kind: imanager-base
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSjkuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSnJkV0psTFhONWMzUmxiU0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUpyZFdKbGNtNWxkR1Z6TFdSaGMyaGliMkZ5WkMxMGIydGxiaTF6WW5GcWJDSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSnJkV0psY201bGRHVnpMV1JoYzJoaWIyRnlaQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbVJpWVRreVltWmlMVGswWXpjdE1URmxPQzA1TlRoaExUQXlOVEF3TURBd01EQXdNU0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwcmRXSmxMWE41YzNSbGJUcHJkV0psY201bGRHVnpMV1JoYzJoaWIyRnlaQ0o5LnVXUjJYRFZRVVpxREltQVFEN0tsVTdIYTZOWFNvR21qVm16MXpjNzd5WkNfUEd4dXQ5MGdpdDh5WUZnVEFOZ1V6UEtqSE9EeHNxWHBDOHNKOWQ3MXNHNEVvRzdVWlZDODZvOEE5VlA5N0lyNnJGU2lSNkdOQ3BvRDJDSjFVNDljQTUxcE9KMjJMV1BscVFYRmYySXpkMnpTeFNTX0QyYWR2YllIa09kYU5HVk5Ba2dTejh2LUZYdE8zWUNKejI5WjZjQ2N3NGZZQ09YUmpFYlE5Q21EOHdBblJIZVNfWm5XcEd3U1VVNER2Z0dmZVV3THh5VWVZRzlOUTk3NUZVLWZmbjBYR1plSFhhQllpMEpIUnFUampMSmFCMTdMZEhUeDFZd0RYaFM4Y1hYSlkyMVdpbVBNQWp4MVktd3hnZERBaTR4cjNMQWZHclZNOWFSSkdVZXJzUQ==
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |
   route:
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'wechat'
   receivers:
   - name: 'wechat'
     wechat_configs:
      - corp_id: 'ww87015933668aaa18'
        to_party: '1'
        agent_id: '1000002'
        api_secret: 'w_sxF80QHT3qJ2y3whmcBqYkwim6Vqw-N2L-_axb04w'
        message: '{{ template "wechat.imanager.message" . }}'
   templates:
     - 'templates/*.tmpl'

