apiVersion: 0.1.0
environments:
  dev:
    destination:
      namespace: ks-dev
      server: https://192.168.199.249:6443
    k8sVersion: v1.10.2
    path: dev
  prod:
    destination:
      namespace: ks-prod
      server: https://192.168.199.249:6443
    k8sVersion: v1.10.2
    path: prod
kind: ksonnet.io/app
libraries:
  redis:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    name: redis
    registry: incubator
name: guestbook
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
