apiVersion: v1
kind: Pod
metadata:
  name: gpu-cuda8
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:8.0-runtime-ubuntu16.04
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs

