apiVersion: v1
kind: Pod
metadata:
  name: nvidia-hashcat
spec:
  containers:
    - name: nvidia-container-hashcat
      image: openthings/hashcat
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
