apiVersion: v1
kind: Pod
metadata:
  name: nvidia-hashcat
spec:
  containers:
    - name: nvidia-container
      image: openthings/hashcat:latest
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
