apiVersion: v1
kind: Pod
metadata:
  name: gpu-opencl
spec:
  containers:
    - name: nvidia-container
      image: nvidia/opencl:devel-ubuntu16.04
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs

